version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - vendor:/var/www/vendor
    environment:
      PHP_IDE_CONFIG: "serverName=zoo"

  #Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: zoo
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  mysql_data:
    driver: local
  vendor:
